apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-parent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dori654/Portfolio-Develeap.git
    targetRevision: HEAD
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true