apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-agency-stack
  namespace: argocd
spec:
  project: default
  source:
    path: applications/app
    repoURL: git@github.com:dori654/Portfolio-Develeap-GitOps.git
    targetRevision: HEAD
    helm:
      releaseName: cat-agency
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cat-agency
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true