apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 51.2.0
    helm:
      releaseName: prometheus-stack
      values: |
        grafana:
          adminPassword: admin123
          service:
            type: ClusterIP
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
            - grafana.cat-agency.local
            tls:
            - secretName: grafana-tls
              hosts:
              - grafana.cat-agency.local
        prometheus:
          prometheusSpec:
            evaluationInterval: 30s
            scrapeInterval: 30s
            retention: 15d
          service:
            type: ClusterIP
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
            - prometheus.cat-agency.local
            tls:
            - secretName: prometheus-tls
              hosts:
              - prometheus.cat-agency.local
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true