apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-infra
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dori654/Portfolio-Develeap-GitOps.git
    targetRevision: HEAD
    path: infra/core
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
