apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    chart: elasticsearch
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    helm:
      releaseName: elasticsearch
      values: |
        clusterName: "cat-agency-logs"
        nodeGroup: "master"
        
        # Use smaller resources for development
        replicas: 1
        minimumMasterNodes: 1
        
        # Resource limits
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        
        # Volume claim template
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "ebs-gp3"
          resources:
            requests:
              storage: 10Gi
        
        # Simplified security configuration - disable security for now
        esConfig:
          elasticsearch.yml: |
            xpack.security.enabled: false
        
        # Use ClusterIP service (single load balancer approach)
        service:
          type: ClusterIP
        
        # Security context
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
        
        # Health checks
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
            scheme: HTTPS
          initialDelaySeconds: 60
        
        # Anti-affinity for production (optional for dev)
        antiAffinity: "soft"
        
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
