apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: logging-secret
  namespace: logging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: logging-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
  dataFrom:
    - extract:
        key: zvi/quizapp/key
      rewrite:
        - regexp:
            source: "logging-user"
            target: "username"
        - regexp:
            source: "logging-pass"
            target: "password"