{{/* Backend Service */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-backend
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/metrics/prometheus"
    prometheus.io/port: "{{ .Values.backend.service.port }}"

spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend

---
{{/* Frontend Service */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-frontend
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend

---
{{/* Backend Alias Service - matches backend-alias.yaml */}}
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
