apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://helm.elastic.co"
    chart: elasticsearch
    targetRevision: 8.11.0
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1
        
        # Enable security with API key authentication
        esConfig:
          elasticsearch.yml: |
            xpack.security.enabled: true
            xpack.security.authc.api_key.enabled: true
        
        resources:
          requests:
            cpu: "25m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "gp2"
          resources:
            requests:
              storage: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
