apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://helm.elastic.co"
    chart: elasticsearch
    targetRevision: 7.17.3
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1
            
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        
        volumeClaimTemplate:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
        
        # Set appropriate JVM heap size
        esJavaOpts: "-Xmx512m -Xms512m"
        
        # Disable security for development/testing
        esConfig:
          elasticsearch.yml: |
            xpack.security.enabled: false
            xpack.security.http.ssl.enabled: false
            xpack.security.transport.ssl.enabled: false
        
        # For development/testing environments
        antiAffinity: "soft"

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
