apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespa          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host elasticsearch-master.logging.svc.cluster.local
                Port 9200
                Logstash_Format On
                Logstash_Prefix cat-agency
                Logstash_DateFormat %Y.%m.%d
                Include_Tag_Key On
                Tag_Key tag
                Generate_ID On
                Replace_Dots On
                Retry_Limit 5
                Suppress_Type_Name On
                tls Off
                tls.verify Offzers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.45.0
    helm:
      values: |
        logLevel: info
        env:
          - name: FLUENT_ES_USER
            valueFrom:
              secretKeyRef:
                name: logging-secret
                key: username
          - name: FLUENT_ES_PASS
            valueFrom:
              secretKeyRef:
                name: logging-secret
                key: password

        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 1
                Log_Level info
                Parsers_File /fluent-bit/etc/parsers.conf
                Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port 2020
                Health_Check On

          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                Multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 10MB
                Skip_Long_Lines On
                Refresh_Interval 5
                Read_from_Head On

          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Kube_URL https://kubernetes.default.svc:443
                Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
                Kube_Tag_Prefix kube.var.log.containers.
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On
                Buffer_Size 32k

            [FILTER]
                Name parser
                Match kube.*
                Key_Name log
                Parser json
                Reserve_Data On
                Preserve_Key On

            [FILTER]
                Name modify
                Match kube.*
                Add cluster cat-agency-cluster
                Add environment production

          customParsers: |
            [PARSER]
                Name json
                Format json
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%L
                Time_Keep On

          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host elasticsearch-master.logging.svc.cluster.local
                Port 9200
                HTTP_User ${FLUENT_ES_USER}
                HTTP_Passwd ${FLUENT_ES_PASS}
                Logstash_Format On
                Logstash_Prefix cat-agency
                Logstash_DateFormat %Y.%m.%d
                Include_Tag_Key On
                Tag_Key tag
                Generate_ID On
                Replace_Dots On
                Retry_Limit 5
                Suppress_Type_Name On
                tls On
                tls.verify On

            [OUTPUT]
                Name stdout
                Match kube.*
                Format json_lines

        # Ensure proper permissions
        podSecurityContext:
          runAsUser: 0

        # Mount host paths for log collection
        daemonSetVolumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
          - name: etcmachineid
            hostPath:
              path: /etc/machine-id
              type: File

        daemonSetVolumeMounts:
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: etcmachineid
            mountPath: /etc/machine-id
            readOnly: true

        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi

        service:
          extraPorts:
            - name: metrics
              port: 2020
              protocol: TCP

        tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true