apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 7.17.3
    helm:
      values: |
        replicas: 1
        
        # Configure Elasticsearch connection with HTTP (security disabled)
        elasticsearchHosts: "http://elasticsearch-master.logging.svc.cluster.local:9200"
        
        # Resource requests and limits
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        
        # Configure service to access Kibana
        service:
          type: LoadBalancer
          port: 5601
        
        # Configure ingress for external access
        ingress:
          enabled: false
          # Uncomment to enable ingress:
          # className: "nginx"
          # hosts:
          #   - host: kibana.local
          #     paths:
          #       - path: /
          #         pathType: Prefix
        
        # Configure default index pattern and dashboards
        kibanaConfig:
          kibana.yml: |
            server.name: kibana
            server.host: "0.0.0.0"
            elasticsearch.hosts: ["http://elasticsearch-master.logging.svc.cluster.local:9200"]
            xpack.security.enabled: false
            monitoring.ui.container.elasticsearch.enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true