apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://helm.elastic.co"
    chart: kibana
    targetRevision: 7.17.3
    helm:
      values: |
        elasticsearchHosts: "http://elasticsearch-master.logging.svc.cluster.local:9200"
        protocol: "http"

        extraEnvs:
          - name: ELASTICSEARCH_USERNAME
            value: "elastic"
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: logging-secret
                key: password

        kibanaConfig:
          kibana.yml: |
            elasticsearch.username: "elastic"
            elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"

        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true